import React, { useState } from "react";
import InformationPopup from '../ui/InformationPopup';

const ConsentSection = ({ data, onChange, errors, userRole }) => {
  const [showPopup, setShowPopup] = useState(false);
  const handleCheckboxChange = (e) => {
    const { name, checked } = e.target;
    onChange({ [name]: checked });
  };
  const handleClosePopup = () => {
    setShowPopup(false);
  };
  const isParticipant = userRole === "participant";
  
  return (
    <div className="space-y-6">
      <h2 className="text-xl font-semibold text-secondary-800">
        Consents and Agreements
      </h2>

      <div className="space-y-4">
        <div className="flex items-start">
          <div className="flex items-center h-5">
            <input
              id="sharingConsent"
              name="sharingConsent"
              type="checkbox"
              checked={data.sharingConsent || false}
              onChange={handleCheckboxChange}
              className="h-4 w-4 rounded border-secondary-300 text-primary-600 focus:ring-primary-500"
            />
          </div>
          <div className="ml-3 text-sm">
            <label
              htmlFor="sharingConsent"
              className="font-medium text-secondary-700"
            >
              I consent to sharing my documents/photos/videos with the camp
              team.
            </label>
            {errors.sharingConsent && (
              <p className="text-red-500 mt-1">{errors.sharingConsent}</p>
            )}
          </div>
        </div>
        <div className="flex items-start">
          <div className="flex items-center h-5">
            <input
              id="availabilityConsent"
              name="availabilityConsent"
              type="checkbox"
              checked={data.availabilityConsent || false}
              onChange={handleCheckboxChange}
              className="h-4 w-4 rounded border-secondary-300 text-primary-600 focus:ring-primary-500"
            />
          </div>
          <div className="ml-3 text-sm">
            <label
              htmlFor="availabilityConsent"
              className="font-medium text-secondary-700"
            >
              I am available from 25<sup>th</sup> - 31<sup>st</sup> August 2025.<span className="text-red-500 mt-1">*</span>
            </label>
            {errors.availabilityConsent && (
              <p className="text-red-500 mt-1">{errors.availabilityConsent}</p>
            )}
          </div>
        </div>

        <div className="flex items-start">
          <div className="flex items-center h-5">
            <input
              id="aiUsageConsent"
              name="aiUsageConsent"
              type="checkbox"
              checked={data.aiUsageConsent || false}
              onChange={(e) => {
                handleCheckboxChange(e);
                e.target.checked && setShowPopup(true);
              }}
              className="h-4 w-4 rounded border-secondary-300 text-primary-600 focus:ring-primary-500"
            />
          </div>
          <div className="ml-3 text-sm">
            <label
              htmlFor="aiUsageConsent"
              className="font-medium text-secondary-700"
            >
              I confirm that all responses are truthful, written by me, and not generated by AI.<span className="text-red-500 mt-1">*</span>
            </label>
            {errors.aiUsageConsent && (
              <p className="text-red-500 mt-1">{errors.aiUsageConsent}</p>
            )}
          </div>
        </div>
      </div>
      <InformationPopup show={showPopup} onClose={handleClosePopup} />

      {/* <div className="bg-primary-50 border border-primary-200 rounded-md p-4 mt-6">
        <p className="text-primary-700 text-sm">
          <span className="font-medium">Note:</span> All consents are required
          to proceed with your application.
        </p>
      </div> */}
    </div>
  );
};

export default ConsentSection;
