const InformationPopup = ({ show, onClose }) => {
  if (!show) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-40 flex items-center justify-center z-50">
      <div className="bg-white p-6 rounded-lg shadow-lg w-96">
        <h2 className="text-lg font-semibold mb-4 text-center">
          AI Usage Policy
        </h2>
        <p className="mb-4 text-center ">
          Please ensure all{" "}
          <strong>your responses are written in your own words.</strong>If
          responses are found to be generated by AI or copied, your application
          may be disqualified.
        </p>

        <div className="text-center mt-3">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-red-500 text-white rounded hover:bg-red-600"
          >
            I agree
          </button>
        </div>
      </div>
    </div>
  );
};

export default InformationPopup;
